### ISSUE TITLE
Self-posts can trigger the bot

### ISSUE THREAD

**Issue by ElijahPepe** [CheAle14/mlapibot#3]
A few of the posts that mlapibot replies to are [self-posts](https://www.reddit.com/r/discordapp/comments/puqutt/dear_discord_compromised_accounts_are_out_of/he4n8yc/?context=3) that aren't there to question if an image is a scam and it would be more likely that a user would just post the image itself. Maybe this could be alleviated by either forcing image posts only or allowing OP to message the bot and remove the comment (or both)?

**Comment by CheAle14** [comment]
Hm, I originally made it look at self posts as there were some users who used the post body to give further context before giving the link (e.g. [this post](https://reddit.com/r/discordapp/comments/pd4yms/is_this_legit/)), and, later on, because there were some things it replied to without using OCR and instead looking at the title/body (e.g. [minecraft server ban appeals](https://old.reddit.com/r/discordapp/comments/o4lsoo/banned_from_the_minecraft_discord_server_for_no/)). Image posts do seem to be the vast majority of responses, and self posts are more likely to be incorrect. I think what I'll do is add an option to ignore self posts on a per-scam basis, so it can ignore self posts for the free Nitro/boost scams, but still act on self posts for other responses that may not be so error prone.

The bot also should already be removing it's comments that are downvoted below 0 (so by two people), which seems to be working well to get rid of the bot's incorrect responses - looking at the last 100 responses, of the posts where the bot has deleted it's own message due to downvotes (18), it did so on average after one hour, with the vast majority being removed within three hours, and the longest taking 283 minutes.
